# -*- coding: utf-8 -*-
"""alpha_vantage.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_AN4QazJZmFEqO3GxmR1NZ0pV1rhTKM9
"""

import requests
!pip install alpha_vantage
import alpha_vantage
key = "3T4MOR0KX9S8IM1M"
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import torch
import time #free version only 5 calls per minute
import json
import csv

#Wrapper functions for alpha vantage API

def real_gdp(functions="REAL_GDP", interval="annual", key="3T4MOR0KX9S8IM1M"):
  url = f'https://www.alphavantage.co/query?function={functions}&interval={interval}&apikey={key}'
  return requests.get(url).json()

def real_gdp_per_cap(function="REAL_GDP_PER_CAPITA", key="3T4MOR0KX9S8IM1M"):
  url = f"https://www.alphavantage.co/query?function={function}&apikey={key}"
  return requests.get(url).json()

def treasury_yield(function="TREASURY_YIELD", interval="monthly", maturity="10year", key="3T4MOR0KX9S8IM1M"):
  url = f"https://www.alphavantage.co/query?function={function}&interval={interval}&maturity={maturity}&apikey={key}"
  return requests.get(url).json()

def federal_funds_rate(function="FEDERAL_FUNDS_RATE", interval="monthly", key="3T4MOR0KX9S8IM1M"):
  url = f'https://www.alphavantage.co/query?function={function}&interval={interval}&apikey={key}'
  return requests.get(url).json()

def cpi(function="CPI", interval="monthly", key="3T4MOR0KX9S8IM1M"):
  url = f'https://www.alphavantage.co/query?function={function}&interval={interval}&apikey={key}'
  return requests.get(url).json()

def inflation(function="INFLATION", key="3T4MOR0KX9S8IM1M"):
  url = f'https://www.alphavantage.co/query?function={function}&apikey={key}'
  return requests.get(url).json()

def inflation_expectation(function="INFLATION_EXPECTATION", key="3T4MOR0KX9S8IM1M"):
  url = f'https://www.alphavantage.co/query?function={function}&apikey={key}'
  return requests.get(url).json()

def consumer_sentiment(function="CONSUMER_SENTIMENT", key="3T4MOR0KX9S8IM1M"):
  url = f'https://www.alphavantage.co/query?function={function}&apikey={key}'
  return requests.get(url).json()

def retail_sales(function="RETAIL_SALES", key="3T4MOR0KX9S8IM1M"):
  url = f'https://www.alphavantage.co/query?function={function}&apikey={key}'
  return requests.get(url).json()

def durable_goods_orders(function="DURABLES", key="3T4MOR0KX9S8IM1M"):
  url = f'https://www.alphavantage.co/query?function={function}&apikey={key}'
  return requests.get(url).json()

def unemployment_rate(function="UNEMPLOYMENT", key="3T4MOR0KX9S8IM1M"):
  url = f'https://www.alphavantage.co/query?function={function}&apikey={key}'
  return requests.get(url).json()

def nonfarm_payroll(function="NONFARM_PAYROLL", key="3T4MOR0KX9S8IM1M"):
  url = f'https://www.alphavantage.co/query?function={function}&apikey={key}'
  return requests.get(url).json()

data = []

data.append(real_gdp())
data.append(real_gdp_per_cap())
data.append(treasury_yield())
data.append(federal_funds_rate())
time.sleep(61)
data.append(cpi())
data.append(inflation())
data.append(inflation_expectation())
data.append(consumer_sentiment())
time.sleep(61)
data.append(retail_sales())
data.append(durable_goods_orders())
data.append(unemployment_rate())
data.append(nonfarm_payroll())

from google.colab import drive
drive.mount('/content/drive')

data_file_director = '/content/drive/MyDrive/Colab Notebooks/Project/macro_data.json'

with open(data_file_director, 'w') as file:
  json.dump(data, file, indent=4)

def new_and_settlement(key, function="NEWS_SENTIMENT", tickers="", topics="economy_macro"):
  url = f'https://www.alphavantage.co/query?function={function}'
  if tickers:
    url += f"&tickers={tickers}"
  if topics:
    url += f"&topics={topics}"
  url += f"&apikey={key}"
  return requests.get(url).json()

def intraday_extended(key, symbol="SPY", interval="60min", slices="year1month1", adjusted="true"):
  url = f"https://www.alphavantage.co/query?function=TIME_SERIES_INTRADAY_EXTENDED&symbol={symbol}&interval={interval}&slice={slices}"
  if adjusted == 'false':
    url += "&adjusted=false"

  url += f"&apikey={key}"

  with requests.Session() as s:
    download = s.get(url)
    decoded_content = download.content.decode('utf-8')
    cr = csv.reader(decoded_content.splitlines(), delimiter=',')
    my_list = list(cr)
    for row in my_list:
        print(row)

def time_series_weekly(key, symbol="SPY", datatype=""):
  url = f"https://www.alphavantage.co/query?function=TIME_SERIES_WEEKLY_ADJUSTED&symbol={symbol}"
  if datatype:
    url += f"&datatype={datatype}"
  url += f"&apikey={key}"
  return requests.get(url).json()


label_data = time_series_weekly(key, symbol='VIX')

print(label_data)


label_file_director = '/content/drive/MyDrive/Colab Notebooks/Project/volitility_index.json'
with open(label_file_director, 'w') as file:
  json.dump(label_data, file, indent=4)

!pip install quandl
# import quandl

# vix = quandl.get("CBOE/VIX")
# vix_close = vix['VIX Close']
# print("VIX:\n%s" %vix_close[-15:])